### ISSUE TITLE
destroys switch to tab behaviour

### ISSUE THREAD

**Issue by nehrwert** [kidproquo/supertab#2]
hi,

thx for the effort of making this useful addon. But there is a problem for me with the addon:
it breaks firefox switch-to-tab behavior. switch to tab is the feature that allows you to find an open tab through typing keyword/the beginning of the address in the address bar of another tab. in the drop down menu of the address bar you can select the open tab and switch to it. sadly this doesn't work while supertab is enabled.

thy again for your work!

**Comment by kidproquo** [comment]
Thanks for the feedback! I am not able to reproduce this issue. I am running FF 26, with Supertab 0.66 on Win7. Switch to tab feature works. I had no idea that such a feature exists :-). Supertab works as well. Can you do a screen capture video and post it on YouTube?

Thanks again.

**Comment by nehrwert** [comment]
Thank you for the fast answer. I just after reading it realized that i didn't restart firefox after the install. After the restart it does work! I'm sorry for the inconvenience and will colse this issue.

Thanks again!
